### ISSUE TITLE
Test suite stopping after 10 tests; no rocks in browser

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/javascript-rock-dodger#12]
**Track:** BootCamp Prep (learn-co-students)

**Branch:** Solution

**Issue Summary** 
When running the test suite and checking the game using the IDE (OSX) and httpserver, the test suite stops after running 10 tests, and no rocks are generated when playing the browser game. However, everything works totally fine on a local dev environment ( I tested it on my Mac).

According to one students a number of students have had similar issues. 

@aturkewi

**Comment by aturkewi** [comment]
Closing and adding this note to issue #7
