### ISSUE TITLE
Bootcamp Prep track still has broken test in it for student who cloned today.

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/javascript-rock-dodger#15]
@aturkewi 

Leonardo Guzman cloned this lab for the bootcamp prep today and it still had that broken test in it. Just wanted to let you know that track may need to be redeployed. 

Thanks!

Dakota

**Comment by aturkewi** [comment]
redeployed and `bootcamp-prep-000` is now back in line with canonical
